[package]
name = "SDL-Test"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0.17.3", features = ["build-from-source"] }
glow = "0.16.0"
glam = "0.32.0"

rand = "0.10.0"
shaderc = "0.10.1"
